### ISSUE TITLE
False positive `NDArray` in Jupyter notebook

### ISSUE THREAD

**Issue by eismont21** [crate-ci/typos#1073]
It was fixed for the .py files https://github.com/crate-ci/typos/issues/565, but it is stilling failing in Jupyter notebooks.

**Comment by epage** [comment]
Currently, none of our language-specific terms recognize Jupyter, see https://github.com/crate-ci/typos/blob/master/crates/typos-cli/src/file_type_specifics.rs

iirc Jupyter allows multiple languages in a notebook, making them ore like Markdown, rather than having a way to tell by extension.  Is that right?

What we'd need to address include
- Should naively handle jupyter like we do for markdown (see also #1055)?
- If we handle it, should we assume its mostly Python people and just make it a synonym for Python?
- If we want to handle these "cross-language" files, how far do we take that?  For example, you could have comments in Python code referring to C code that you are using bindings for.
