### ISSUE TITLE
`typos` is hanging on two generated files without any words

### ISSUE THREAD

**Issue by Kijewski** [crate-ci/typos#1088]
* [`comment-depth.txt`](https://github.com/rinja-rs/rinja/blob/2d80cc3524483902a70857da2bd9894164f3a24d/rinja_parser/tests/comment-depth.txt)
* [`filter-recursion.txt`](https://github.com/rinja-rs/rinja/blob/fc1d52d6046b792a0202fba6bbc3ff3995a5c714/rinja_parser/tests/filter-recursion.txt)

My guess would be that some sort of exponential backtracking is happening. I guess the program would ultimately finish.

**Comment by epage** [comment]
Not 100% this is the root cause but it isn't helping...

Our URL and email detection is very rudimentary  With `comment-depth.txt`, we see the whole file as a valid email username, so iterate to the very end and then see no `@` at the end and fail.  So on nearly every byte we are then looking ahead through the entire file, checking every byte.  Twice.

This also means we checking every token type on every byte.  We aren't getting any savings from one capturing 10 or 20 bytes.

Capping email usernames and url userinfo's at 1024 characters makes `typos` take 3s on `comment-depth.txt` **with a debug build**.
