### ISSUE TITLE
False positive `seldomly` -> `seldom`

### ISSUE THREAD

**Issue by joshpetit** [crate-ci/typos#1112]
`Seldomly` is a word, but when typed it is suggested to change it to `seldom`.

v.0.1.26

**Comment by epage** [comment]
https://www.merriam-webster.com/grammar/6-common-hypercorrections-and-how-to-avoid-them/seldomly-for-seldom lists `seldomly` as redundant as `seldom` is an adverb and it has been marked as archaic in dictionaries for over 100 years.

https://www.oed.com/dictionary/seldomly_adv?tab=meaning_and_use#23764287 lists it as obsolete with a date range ending in 1864.

So this seems to fall under more of a style, grammar, correctness issue, rather than strictly typo.  Unsure how opinionated we should be on those.

**Comment by joshpetit** [comment]
Woah, well I learn something new every day. In that case I don't mind it at all, I'll just use seldom haha.
