### ISSUE TITLE
Crash with shell redirection

### ISSUE THREAD

**Issue by fenuks** [crate-ci/typos#264]
Hello, I wanted to test typos, and crashed it trying to check my file. Funny thing, tired of typos, I was thinking of writing something similar in rust, but with use of tree-sitter parsers.

You can reproduce it like that:

```sh
mkdir /tmp/typos-test
cd /tmp/typos-test
cat > test.py << EOF
# tyyypo
is_eror = 1
EOF
```
and then invoke it with
```sh
typos - < test.py
```

```
name = 'typos-cli'
operating_system = 'unix:Arch'
crate_version = '1.0.2'
explanation = '''
Panic occurred in file 'src/policy.rs' at line 90
'''
cause = '`walk()` should be called first'
method = 'Panic'
backtrace = ''
```

I tried command on largish project, and it does detect few typos, but it didn't find any in above `test.py` file. Is there something I miss here?

```sh
$ typos --words
test
py
tyyypo
is
eror
```
clearly proves that it is checked, and words I consider misspelled are printed out.

**Comment by epage** [comment]
Need to go use `assert_cmd` to cover this case.

> Funny thing, tired of typos, I was thinking of writing something similar in rust, but with use of tree-sitter parsers.

Feel free to reuse parts of `typos` for that! I can move things from the CLI to the lib as you need them (like the dictionaries)

**Comment by epage** [comment]
I've got a PR that reproduces a `panic` and fixes it but its a different `panic` which surprises me.

**Comment by epage** [comment]
Oh, I hit a different panic because I was running a debug build and so my `debug_assert` was hit before we got to the case that it panicked for you.

**Comment by epage** [comment]
v1.0.3 is now published.  CI should be uploading pre-built binaries shortly

**Comment by fenuks** [comment]
> Feel free to reuse parts of typos for that! I can move things from the CLI to the lib as you need them (like the dictionaries)

Thank you! I'll keep that in mind when/if I motivate myself to actually try to evaluate this idea. Tree sitter would be obviously slower, but my main use case would be using it in git hook on modified files only or on diff.

> v1.0.3 is now published. CI should be uploading pre-built binaries shortly

You've fixed this bug in impressive time. I wrote PKGBUILD for myself to package it, might as well publish it to AUR.

> it didn't find any in above test.py file. Is there something I miss here?

Could you please clarify why no typos are detected here? Is this expected?

**Comment by epage** [comment]
> Could you please clarify why no typos are detected here? Is this expected?

Most spell checkers are integrated into an editor in a way that they are only providing suggestions.  Even when they auto-correct, they make sure the user knows they did this.  This gives them the flexibility to not always be correct.  They are implemented off of a model where there is a definitive list of words and when spell checking a word, they look for the closest match.  This also takes a performance hit which is fine because they effectively do not need to run much faster than the user typing.

`typos` is meant to run automatically, always auto-correcting or failing CI.  There is no room for error in this model.  So instead of a lit of blessed words, `typos` has a list of known typos and their correct spelling.  `typos` is also expected to run on an entire repo, so ti needs to be fast, and this model is faster because it is just a look up, rather than a closest-match.

See [design.md](https://github.com/crate-ci/typos/blob/master/docs/design.md) for some of the design philosophy behind `typos`.

**Comment by fenuks** [comment]
Thank you for detailed answer. Your rationale makes sense, especially if one wants to auto-fix all typos, although it's also limited in what will be detected if user just wants to check for typos without autocorrection. In such case more aggressive approach could be taken without dramatically increasing number of false positives. That being said, it's an interesting project, and I will try to add it to CI linting phrase. :)
