### ISSUE TITLE
Detect and ignore base64 encoded data

### ISSUE THREAD

**Issue by Skylion007** [crate-ci/typos#287]
When trying to run typos on iPython notebooks like Google Colabs, it destroys all the base64 data inside of the notebook [banana.jpg]. Base64 is not necessarily a spelling error: For example running it in this folder mangles the notebooks: https://github.com/facebookresearch/habitat-sim/tree/master/examples/tutorials/colabs .

**Comment by epage** [comment]
Short term, I'd recommend
```
[type.jupyter]
check-file = false
```
See https://github.com/crate-ci/typos#false-positives

Longer term, we are discussing in #270 for ignoring hashes, and base64.  Since that issue is titled for hashes, I'll leave this one open to track also addressing base64, since they might not be addressed at the same time.
