### ISSUE TITLE
False positive for BRE

### ISSUE THREAD

**Issue by scop** [crate-ci/typos#436]
The acronym BRE (short for (POSIX) Basic Regular Expression) gets a false positive hit from typos, suggesting BE or BRIE.

**Comment by epage** [comment]
We can't distinguish between straight acronyms and SCREAMING_CASE words, so this comes down to how we do want to treat these as words.

Our options
- Have people include abbreviations in their dictionary
- Include this in our dictionary
- Have a configurable min word length to filter out TLAs
  - [scspell does this](https://github.com/myint/scspell/blob/00ed694359f51a2cacc58be1d7e7e252826a39b4/scspell/__init__.py#L523)

Having a list of acronyms to cover would give me a better sense for the impact of including them.

Short term, I'm going to go ahead with min word lengths.

**Comment by epage** [comment]
Bleh, the way concerns are separated, it will take some re-work to add min-length checks

**Comment by epage** [comment]
I'm leaning towards BRE being a fairly specific domain word and would recommend people putting it in their dictionary, rather than a more general solution.

We can revisit this depending on what additional input people have.

**Comment by your-diary** [comment]
Having the same issue.

While I partly understand the reason this issue was closed, denying "BRE" while accepting "PCRE" feels unnatural to me.

While PCRE is famous, I believe BRE (and ERE) are more widely adopted in practice:

- `vim`, `sed`, `grep`, `git log -L`, `diff -I`, etc. use BRE by default.

- `rg`, `fd`, etc. use ERE by default.

- Regex libraries in modern languages (e.g. `regex` crate in Rust) tend to use customized ERE.
