### ISSUE TITLE
compare with codespell  false negative 

### ISSUE THREAD

**Issue by mikulely** [crate-ci/typos#489]
based on the some input，typos found more typos than codespell，but with one nit:

vim release.sh

```
26 # remote call fot the jenkins job
```

test with typos, report nothing:

```
# typos --format=brief
```

codespell found typos `fot`

```
# codespell -q 3
release.sh:26: fot ==> for, fit, dot, rot, cot, got, tot, fog
```
is there any way to optimize on this? Thx.

**Comment by epage** [comment]
Both spell checkers are limited by their dictionaries.  In this case, codespell has an item that typos doesn't.  We can always carry these over.

In general, because of the approach both tools use for correcting (curated list of types), it is always a game of whack-a-mole finding more typos for the benefit of reduced false positives.

**Comment by mikulely** [comment]
I've found [the item within codespell dict.txt](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt#L14946) ,should we sync this with https://github.com/crate-ci/typos/blob/master/crates/codespell-dict/assets/dictionary.txt periodicly?
