### ISSUE TITLE
.vim file not being detected in typos.toml

### ISSUE THREAD

**Issue by mdeguzis** [crate-ci/typos#567]
My config is below. Vim reports the filetype of `configuration/dotfiles/vim/autoload/plug.vim` as `vim`, but it won't skip the filetype, only if I add it to the `[files]` section. When I do that, the other `*.vim` files are skipped, but not `/local/home/deguzim/src/DeGuzim-Config/configuration/dotfiles/vim/autoload/plug.vim`...

version:
```
$ typos --version
typos-cli 1.11.1
```

```
[files]
# For some reason, type.vim is not being picked up
# Add any exceptions to extend-exclude below...
extend-exclude = ["*.vim"]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"

[default.extend-words]
bre = "bre"

[type.tmux]
extend-glob = ["*tmux*"]
check-file = false

[type.rust]
extend-glob = []

[type.zsh]
extend-glob = [".*zsh.*"]
check-file = false

[type.cert]
extend-glob = []
check-file = false

[type.wiki]
extend-glob = ["*.wiki"]
check-file = false

[type.json]
extend-glob = []
check-file = false

[type.css]
extend-glob = []
check-file = false

[type.lock]
extend-glob = []
check-file = false

[type.vim]
check-file = false


```

**Comment by epage** [comment]
Could you provide more explicit reproduction steps (create these files, create this config, run this command, see this output but instead I want that output)?  There is just enough ambiguity that it will take some digging around to make sure I am responding to the problem you are actually having rather than a misunderstanding of it.

**Comment by epage** [comment]
We improved some file type detection for #487 but that fix went in before this was filed.  I am adding a `--file-types` flag to help in debugging these issues.  Most likely the culprit is that we detect `.vim` as `vimscript` instead.  

Without further information, I'm going to go ahead and close this.
