### ISSUE TITLE
Typos renames packages on my pyproject.toml

### ISSUE THREAD

**Issue by ericriff** [crate-ci/typos#614]
I have a project that has a `pyproject.toml` file to list python dependencies (using poetry).
typos renames one of the modules
```diff
diff --git a/pyproject.toml b/pyproject.toml
index 74b1587c8f2..a7c90c5420e 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -30,7 +30,7 @@ numpy = "1.19.2"
 scipy = "*"
 yattag = "*"
 lark-parser = "*"
-empy = "*"
+empty = "*"
 catkin-pkg = "*"
 mkdocs-mermaid2-plugin = "^0.5.0"
 bs4 = "^0.0.1"
```

**Comment by epage** [comment]
When it comes to people, businesses, and packages, we can't predict what all names will be in use. Users can configure per language and global overrides for these. When a name is pervasive enough in an ecosystem, we can build it in.

I'm not familiar with empy but its been a while since I've done serious python and I was limited in what sub-communities I dealt with (e.g. Not numpy, pandas, etc), so I can't judge this one.

**Comment by ericriff** [comment]
Got it, makes sense.
Going though the docs about false positives and how to suppress them you list two examples, one for words and one for identifiers.
```
[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# Don't correct the surname "Teh"
teh = "teh"
```
Could you clarify the difference between a word and an identifier?

**Comment by epage** [comment]
Identifiers are made up of words.

You can see this by running `typos --identifiers` and `typos --words`

**Comment by ericriff** [comment]
I'd add those lines to the readme. I'll close this now. Thanks for the help.
Awesome tool BTW.
