### ISSUE TITLE
Parse PHP imports

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#746]
```diff
- use App\Http\Controllers\SolutionsContoller;
+ use App\Http\Controllers\SolutionsController;
```

This typos was caught everywhere but in PHP imports (use statement).
Could we resolve this?

**Comment by epage** [comment]
PHP uses `\`?  Yikes

With `\`, we can end up with
- File paths, string literals, PHP imports, etc where `\not\tree` should be split into `not` and `tree`
- Common form of strings where `\not\tree` should be `ot` and `ree` because `\n` and `\t` are escaped.

So far, we've mostly taken the approach of [ignoring content after a `\`](https://github.com/crate-ci/typos/blob/master/crates/typos/src/tokens.rs#L411) to reduce the chance of false positives which tends to be a higher priority than identifying types as we want to be able to be run in CI and in pre-commit hooks

**Comment by szepeviktor** [comment]
I could manage without imports being detected. I have many more tools to spot missing imports as the imported class is always used later in the source code.

You seem to be up to the task!

**Comment by epage** [comment]
In that case, I'm going to go ahead and close this
