### ISSUE TITLE
Find URL encoded typos

### ISSUE THREAD

**Issue by szepeviktor** [crate-ci/typos#847]
How to find "alligned" in `pypi%20browse%20alligned.gif`?
Please help me.

**Comment by epage** [comment]
This is getting caught in our check to avoid problems with `printf` formatting (`%falligned` should be assumed to be `falligned`).

As our goal is
- Fast
- Low false positives 

We erred on the side of more false negatives by just ignoring everything after a `%`.  As this is expected behavior, I'm going to go ahead and close.  If there is a reason we need to revisit, let us know!
